---
fixtures:
  repositories:
    stdlib:
      ref: "4.12.0"
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
    mysql:
      ref: "3.8.0"
      repo: "https://github.com/puppetlabs/puppetlabs-mysql"
    staging:
      ref: "v1.0.7"
      repo: "https://github.com/voxpupuli/puppet-staging"
    docker:
      ref: "v5.3.0"
      repo: "https://github.com/garethr/garethr-docker"
    apt:
      ref: "2.2.2"
      repo: "https://github.com/puppetlabs/puppetlabs-apt"
    vision_mysql:
      ref: "origin/production"
      repo: "https://github.com/vision-it/vision-mysql"

  symlinks:
    vision_intranet: '#{source_dir}'
